package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.BuildType
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a buildType with id = 'Manual1_Manual2_Manula2bc'
in the project with id = 'Manual1_Manual2', and delete the patch script.
*/
create(RelativeId("Manual1_Manual2"), BuildType({
    id("Manual1_Manual2_Manula2bc")
    name = "manula2bc"
}))

