package patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*
import jetbrains.buildServer.configs.kotlin.v2019_2.vcs.GitVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a vcsRoot with id = 'Manual1_S'
in the project with id = 'Manual1', and delete the patch script.
*/
create(RelativeId("Manual1"), GitVcsRoot({
    id("Manual1_S")
    name = "s"
    url = "https://github.com/AChubatova/composite"
    branch = "refs/heads/master"
    authMethod = password {
    }
}))

